<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WhiteKnuckleMP.Networking\WhiteKnuckleMP.Networking.csproj" />
      <ProjectReference Include="..\WhiteKnuckleMP.Utils\WhiteKnuckleMP.Utils.csproj" />
    </ItemGroup>

</Project>
